theme: jekyll-theme-minimal
repository: nineties/aboutme

title: About Me
logo: https://pbs.twimg.com/profile_images/797490964/PICT0031__1__Cartoonizer_1_400x400.jpg


github:
    - project_tagline: test
    - is_user_page: true
    - is_project_page: false

google_analytics: UA-129434657-1
